#!/bin/bash
if [ "$#" -ne 1 ]; then
  echo "Usage: ./setuptunnel /root/privatekey.ppk (2nd arg is path to private key)" >&2
  exit 1
fi
crontab -l > /tmp/dump
echo " * * * * * /root/rssh/reverse_ssh" $1 "2>/root/debug.log" >> /tmp/dump
crontab /tmp/dump

